### ISSUE TITLE
weird time consumption in cpu mode contrast with gpu mode?

### ISSUE THREAD

**Issue by TITC** [IshitaTakeshi/PCANet#11]
> CPU mode
fit time consumed: 8.314415125250001  min
transform time consumed: 12.052835527216669  min
classifier time consumed: 38.05203061906666  min

> GPU mode
fit time consumed: 8.892656507983332  min
transform time consumed: 70.50472424445  min
classifier time consumed: 27.279071853850002  min

----------
>GPU env [Google Colab]

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 4304382213728762034
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15695426368
locality {
  bus_id: 1
  links {
  }
}
incarnation: 1752073005966876758
physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"
]

----------
it's consumed more than CPU mode.

**Comment by TITC** [comment]
![image](https://user-images.githubusercontent.com/35098797/108597784-c8d3b000-73c5-11eb-91b1-41d7a920c61c.png)
![image](https://user-images.githubusercontent.com/35098797/108597816-e86ad880-73c5-11eb-9425-344f0c71b338.png)

**Comment by IshitaTakeshi** [comment]
Maybe consuming time when sending data to GPU?
If so, lines after ```if gpu_enabled():``` in [pcanet.py](https://github.com/IshitaTakeshi/PCANet/blob/master/pcanet.py) should be the bottlenecks.

You can profile using [line_profiler](https://github.com/rkern/line_profiler)

**Comment by TITC** [comment]
thanks for your guidance.
