### ISSUE TITLE
Can't save PCANet model

### ISSUE THREAD

**Issue by LuxunHuang** [IshitaTakeshi/PCANet#3]
When i use "python3 run_mnist.py --gpu 0 train --out result" to train PCANet ,but get this error message
_pickle.PicklingError: Can't pickle <class 'pcanet.PCANet'>: it's not the same object as pcanet.PCANet

How can I solve this problem?
thank you

**Comment by IshitaTakeshi** [comment]
Thank you for the report.
It was because of the odd behavior of pickle and now the problem should be solved.

**Comment by LuxunHuang** [comment]
It's work, thank you.
