### ISSUE TITLE
ValueError: array must not contain infs or NaNs  while running run_mnist.py

### ISSUE THREAD

**Issue by arunadevikaruppasamy** [IshitaTakeshi/PCANet#4]
C:\Users\s121293.SQU\PCANet>python  run_mnist.py --gpu -1 train --out result
Training the model...
C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py:274: RuntimeWarning: overflow encountered in long_scalars
  np.sqrt((self.n_samples_seen_ * n_samples) /
C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py:275: RuntimeWarning: invalid value encountered in sqrt
  n_total_samples) * (self.mean_ - col_batch_mean)
Traceback (most recent call last):
  File "run_mnist.py", line 79, in <module>
    pcanet, classifier = train(train_set)
  File "run_mnist.py", line 46, in train
    pcanet.fit(images_train)
  File "C:\Users\s121293.SQU\PCANet\pcanet.py", line 322, in fit
    self.pca_l1.partial_fit(patches)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py", line 279, in partial_fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\linalg\decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_util.py", line 238, in _asarray_validated
    a = toarray(a)
  File "C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by IshitaTakeshi** [comment]
Seems overflow encountered in scikit-learn.
What is the version of your scikit-learn?

**Comment by arunadevikaruppasamy** [comment]
HI

         The scikit-learn version is 0.20.2.
         What i need to do to overcome this issue? pls guide me. Thank you

**Comment by arunadevikaruppasamy** [comment]
The scikit-learn version is 0.20.2.

**Comment by IshitaTakeshi** [comment]
I updated the repository so please update your local one and try again

**Comment by arunadevikaruppasamy** [comment]
Thank you.

**Comment by arunadevikaruppasamy** [comment]
Thank you so much for your help.

**Comment by arunadevikaruppasamy** [comment]
HI IshitaTakeshi/PCANet
    I have downloaded and the installation was done but while running
run_mnist.py ,i am getting the following error. Could you please help me.
Sorry to trouble you again

C:\Users\s121293.SQU\Downloads\PCANet-master\PCANet-master>python
run_mnist.py --gpu -1 train --out result
Training the model...
Training PCANet
C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py:274:
RuntimeWarning: overflow encountered in long_scalars
  np.sqrt((self.n_samples_seen_ * n_samples) /
C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py:275:
RuntimeWarning: invalid value encountered in sqrt
  n_total_samples) * (self.mean_ - col_batch_mean)
Traceback (most recent call last):
  File "run_mnist.py", line 83, in <module>
    pcanet, classifier = train(train_set)
  File "run_mnist.py", line 48, in train
    pcanet.fit(images_train)
  File
"C:\Users\s121293.SQU\Downloads\PCANet-master\PCANet-master\pcanet.py",
line 322, in fit
    self.pca_l1.partial_fit(patches)
  File
"C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\decomposition\incremental_pca.py",
line 279, in partial_fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File
"C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\linalg\decomp_svd.py",
line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File
"C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_util.py",
line 238, in _asarray_validated
    a = toarray(a)
  File
"C:\Users\s121293.SQU\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\function_base.py",
line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

C:\Users\s121293.SQU\Downloads\PCANet-master\PCANet-master>

**Comment by IshitaTakeshi** [comment]
But didn't occur in my environment

**Comment by arunadevikaruppasamy** [comment]
HI ishitaTakeshi/PCANet

    whether i need to change python version ?
my python version is the following one,

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

can you please guide me? sorry for the trouble

**Comment by IshitaTakeshi** [comment]
Can you try to run on ubuntu?

**Comment by arunadevikaruppasamy** [comment]
ok i will try. thank you for your support.

**Comment by arunadevikaruppasamy** [comment]
I saved the model when i trained PCANet.For Testing i run the following command ,could you please help me for resolving the error
sudo python run_mnist.py --gpu -1 test –pretrained-model ~/Downloads/PCANet-master/result

usage: run_mnist.py [-h] [--gpu GPU] {train,test} ...
run_mnist.py: error: unrecognized arguments: –pretrained-model /home/fyp/Downloads/PCANet-master/result

**Comment by arunadevikaruppasamy** [comment]
Hi ishitaTakeshi/PCANet

i trained the model and saved it .

I saved the model when i trained PCANet. For Testing i run the following
command ,
sudo python run_mnist.py --gpu -1 test –pretrained-model
~/Downloads/PCANet-master/result

usage: run_mnist.py [-h] [--gpu GPU] {train,test} ...
run_mnist.py: error: unrecognized arguments: –pretrained-model
/home/fyp/Downloads/PCANet-master/result

could you please help me for resolving the error . I think i made some
mistake while running test

**Comment by arunadevikaruppasamy** [comment]
it is running in ubuntu .thanku so much
