### ISSUE TITLE
only 41% accuracy for our own dataset (4 classes-each102 images)

### ISSUE THREAD

**Issue by arunadevikaruppasamy** [IshitaTakeshi/PCANet#7]
I have used this PCANet code for the dataset which contains cat(102),dog(102),horses(102),human images(102) of total 808 images.
For training , i gave 600 images and 208 images for testing. but showed poor performance than tradition CNN network and  VGG16
please can you help me to resolve this issue

**Comment by IshitaTakeshi** [comment]
Not an issue of this software
